"""Integration/browser checks for the studio and local privacy features."""
from pathlib import Path
from urllib.parse import urlsplit
from http.server import ThreadingHTTPServer,SimpleHTTPRequestHandler
import threading
from playwright.sync_api import sync_playwright,expect
root=Path(__file__).resolve().parents[1]
class Handler(SimpleHTTPRequestHandler):
 def translate_path(self,path):return str(root/'dist'/urlsplit(path).path.removeprefix('/healthapp/'))
 def log_message(self,*args):pass
server=ThreadingHTTPServer(('127.0.0.1',8769),Handler)
threading.Thread(target=server.serve_forever,daemon=True).start()
def read(page,key,raw=False):
 return page.evaluate('''async([key,raw])=>{const r=indexedDB.open('healthup');const db=await new Promise(resolve=>r.onsuccess=()=>resolve(r.result));const get=k=>new Promise(resolve=>{const r=db.transaction(k).objectStore(k).get(k==='crypto'?'device-key':'current');r.onsuccess=()=>resolve(r.result)});const value=await get(key);if(raw||!value?.encrypted)return value;const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(value.iv)},await get('crypto'),bytes(value.cipher));return JSON.parse(new TextDecoder().decode(clear))}''',[key,raw])
def stored(page,key,predicate):
 for _ in range(70):
  result=read(page,key)
  if predicate(result):return result
  page.wait_for_timeout(100)
 raise AssertionError((key,result))
try:
 with sync_playwright() as p:
  browser=p.chromium.launch(executable_path='/usr/bin/chromium',args=['--no-sandbox'])
  context=browser.new_context(viewport={'width':390,'height':844})
  page=context.new_page();errors=[];requests=[]
  page.on('pageerror',lambda error:errors.append(str(error)))
  page.on('request',lambda request:requests.append(request.url))
  url='http://127.0.0.1:8769/healthapp/'
  page.goto(url,wait_until='networkidle')
  page.locator('.landing-header .button').click()
  page.get_by_label('Your name, if you’d like').fill('Riley')
  page.get_by_label('I am 18 or older.',exact=True).check()
  page.get_by_label('I acknowledge the wellness purpose and privacy notice; local entries are not monitored.',exact=True).check()
  page.get_by_role('button',name='Start my HealthUp').click()
  page.locator('#care-time').select_option('2')
  expect(page.locator('.care-prompt')).to_contain_text('2-minute')
  page.get_by_role('button',name='Start 2-minute activity',exact=True).click()
  expect(page.locator('dialog .activity-clock')).to_be_visible()
  stored(page,'timer',lambda t:t and t['duration']==120)
  page.locator('dialog').get_by_role('button',name='Pause',exact=True).click()
  stored(page,'timer',lambda t:t and t['endsAt']==0)
  page.locator('dialog').get_by_role('button',name='Resume',exact=True).click()
  page.get_by_role('button',name='Close dialog').click()
  page.locator('#care-time').select_option('5')
  expect(page.locator('.care-prompt')).to_contain_text('5-minute')
  stored(page,'timer',lambda t:t and t['total']==300 and '5-minute' in t['kind'])
  page.locator('.mobile-more').get_by_role('button',name='Studio',exact=True).click()
  page.get_by_label('Practice category').select_option('movement')
  page.get_by_role('button',name='Start 2-minute activity',exact=True).click()
  timer=stored(page,'timer',lambda t:t and t['duration']==120 and t['category']=='movement')
  assert '120 seconds' in timer['steps'][-1]
  page.get_by_role('button',name='Stop this activity',exact=True).click()
  page.screenshot(path=str(root/'tests/studio-mobile.png'),full_page=True)
  print('PASS: duration-specific practices, category, random choice, modal, pause/resume, active duration changes',flush=True)
  page.locator('.mobile-more').get_by_role('button',name='Journal',exact=True).click()
  page.get_by_role('button',name='Dream book',exact=True).click()
  page.get_by_role('button',name='Write an entry',exact=True).click()
  page.get_by_label('Title',exact=True).fill('A glass moon')
  page.get_by_label('Your entry',exact=True).fill('A private dream, remembered in my own words.')
  page.get_by_label('Tags, separated by commas').fill('calm,moon')
  page.get_by_role('button',name='Save my entry',exact=True).click()
  stored(page,'wellness',lambda w:len(w['journals'])==1)
  raw=read(page,'wellness',True)
  assert raw['encrypted'] and 'private dream' not in str(raw)
  page.get_by_role('button',name='Favorite A glass moon',exact=True).click()
  stored(page,'wellness',lambda w:w['journals'][0]['favorite'])
  page.get_by_label('Search your entries',exact=True).fill('moon')
  expect(page.locator('.journal-entry')).to_have_count(1)
  page.reload(wait_until='networkidle')
  page.get_by_role('button',name='Dream book',exact=True).click()
  expect(page.locator('.journal-entry')).to_contain_text('A glass moon')
  page.get_by_role('button',name='A glass moon',exact=True).click()
  page.get_by_label('Your entry',exact=True).fill('A revised private dream.')
  page.get_by_role('button',name='Save my entry',exact=True).click()
  stored(page,'wellness',lambda w:w['journals'][0]['body']=='A revised private dream.')
  page.get_by_role('button',name='Gratitude',exact=True).click()
  page.get_by_role('button',name='Write an entry',exact=True).click()
  page.get_by_label('Your entry',exact=True).fill('A warm cup helped.')
  page.get_by_role('button',name='Save my entry',exact=True).click()
  stored(page,'wellness',lambda w:len(w['journals'])==2)
  print('PASS: dream/journal CRUD, tags, favorites, search, refresh, encrypted device records, gratitude',flush=True)
  page.locator('.mobile-nav').get_by_role('button',name='You',exact=True).click()
  page.get_by_label('Quiet mode · pause auto-rotating affirmations and daily check-in popups',exact=True).check()
  page.get_by_role('button',name='Export encrypted backup',exact=True).click()
  page.get_by_label('Backup passphrase',exact=True).fill('a private backup passphrase')
  with page.expect_download() as info:page.get_by_role('button',name='Encrypt and download',exact=True).click()
  download=info.value;target=root/'tests'/'temporary-encrypted.json';download.save_as(target)
  assert 'A revised private dream' not in target.read_text()
  page.get_by_label('Import HealthUp backup',exact=True).set_input_files(target)
  expect(page.locator('dialog')).to_contain_text('Unlock your backup')
  page.get_by_label('Backup passphrase',exact=True).fill('a private backup passphrase')
  page.get_by_role('button',name='Unlock and restore',exact=True).click()
  expect(page.locator('dialog')).to_have_count(0)
  target.unlink()
  page.get_by_label('Show optional calorie estimates and meal energy logging',exact=True).uncheck()
  page.locator('.mobile-more').get_by_role('button',name='Food',exact=True).click()
  expect(page.locator('.recipe-card')).to_have_count(100)
  assert 'kcal est.' not in page.locator('.recipe-meta').first.inner_text()
  page.locator('.mobile-more').get_by_role('button',name='Mind',exact=True).click()
  shown=set()
  for _ in range(10):
   text=page.locator('blockquote').inner_text();assert text not in shown;shown.add(text)
   page.get_by_role('button',name='Another thought',exact=False).click()
  print('PASS: passphrase export/import, optional calorie display, non-repeating affirmation cycle, quiet mode',flush=True)
  page.locator('.mobile-more').get_by_role('button',name='Resources',exact=True).click()
  expect(page.get_by_role('link',name='Call 988',exact=True).first).to_be_visible()
  page.get_by_role('button',name='Worldwide',exact=True).click()
  expect(page.locator('.resource-card')).to_contain_text(['Find a Helpline','Befrienders Worldwide','WHO mental health information'])
  page.locator('.mobile-more').get_by_role('button',name='Account',exact=True).click()
  expect(page.locator('.account-unavailable')).to_contain_text('not activated')
  page.get_by_role('button',name='Read the privacy notice',exact=True).click()
  page.get_by_role('button',name='Legal sources',exact=True).click()
  expect(page.locator('.guide-grid')).to_contain_text('Colorado Privacy Act')
  assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
  page.wait_for_function('navigator.serviceWorker.controller!==null',timeout=15000)
  context.set_offline(True)
  page.goto(url+'#journal',wait_until='domcontentloaded')
  page.get_by_role('button',name='Dream book',exact=True).click()
  expect(page.locator('.journal-entry')).to_contain_text('A glass moon')
  assert not any('fonts.googleapis.com' in r or 'fonts.gstatic.com' in r for r in requests)
  assert not errors,errors
  print('PASS: regional support, legal sources, account service fallback, mobile layout, fully local fonts, encrypted offline journal',flush=True)
  browser.close()
finally:server.shutdown()
