import {useState,useEffect} from 'react';
import {Droplets,Utensils,Heart,Activity,Wind,Moon,Plus,ArrowUpRight,Check} from 'lucide-react';
import {useHealth} from './store';
import {Modal} from './ui';
import {uid,dateKey} from './logic';
import {EventEditor} from './Calendar';
import {moods,moodEmoji} from './Progress';
export function Support({onClose}:{onClose:()=>void}){const {state,update}=useHealth();const region=state.preferences.supportRegion||'US';return <Modal title="You don’t have to face this alone." onClose={onClose}><p>If you may act on thoughts of suicide, are seriously injured, or are in immediate danger, call your local emergency number now or go to the nearest emergency department. If possible, reach someone you trust and avoid being alone.</p><label>Your region<select value={region} onChange={e=>update(s=>({...s,preferences:{...s.preferences,supportRegion:e.target.value}}))}><option value="US">United States</option><option value="CA">Canada</option><option value="UK">United Kingdom / Ireland</option><option value="OTHER">Another country</option></select></label>{region==='US'||region==='CA'?<div className="support-box"><h3>Call or text <em>988.</em></h3><p>{region==='US'?'988 Suicide & Crisis Lifeline':'9-8-8 Suicide Crisis Helpline'} offers crisis support. In immediate danger, call 911.</p><div className="actions"><a className="button" href="tel:988">Call 988</a><a className="button secondary" href="sms:988">Text 988</a><a className="text-link" href={region==='US'?'https://988lifeline.org/get-help/':'https://988.ca/'} target="_blank" rel="noreferrer">Official service ↗</a></div></div>:region==='UK'?<div className="support-box"><h3>Samaritans <em>116 123.</em></h3><p>For someone to talk to, call Samaritans. In immediate danger in the UK or Ireland, call 999 or 112.</p><a className="button" href="tel:116123">Call 116 123</a><a className="text-link" href="https://www.samaritans.org/how-we-can-help/contact-samaritan/" target="_blank" rel="noreferrer">Official service ↗</a></div>:<div className="support-box"><h3>Find support <em>near you.</em></h3><p>Crisis numbers vary by country. In immediate danger, use your local emergency service.</p><a className="button" href="https://findahelpline.com/" target="_blank" rel="noreferrer">Find a local helpline ↗</a></div>}<p className="tiny">HealthUp does not monitor your entries, provide crisis response, or contact emergency services automatically. Buttons open your device’s calling or messaging app.</p><details><summary>About HealthUp and medical guidance</summary><p>HealthUp is a personal wellness companion. It does not diagnose, treat, prevent, or monitor medical or mental health conditions. Balance scores, recipe nutrition estimates, trends, and check-ins are informational, not clinical measurements. Seek qualified advice for individualized health, nutrition, exercise, or mental health needs. Do not delay professional care because of something shown here.</p></details></Modal>}
export default function Actions({action,onClose,onSupport}:{action:string;onClose:()=>void;onSupport:()=>void}){const {state,update,notify,go,openAction}=useHealth();const [mood,setMood]=useState<number|null>(null);const [step,setStep]=useState(1);const [includeDetails,setIncludeDetails]=useState(false);const [energy,setEnergy]=useState(3);const [stress,setStress]=useState(3);const [hunger,setHunger]=useState(3);const [sleep,setSleep]=useState(3);const [note,setNote]=useState('');const [amount,setAmount]=useState('');const today=dateKey();useEffect(()=>{if(action==='breathe'){go('mind');onClose()}},[action]);const finish=(message:string)=>{notify(message);onClose()};if(action.startsWith('event'))return <EventEditor title={action.includes(':')?action.slice(action.indexOf(':')+1):''} onClose={onClose}/>;
if(action==='all')return <Modal title="One small, helpful decision." onClose={onClose}><p>Choose what feels useful. Everything is optional.</p><div className="action-sheet">{[[Droplets,'Water','water'],[Utensils,'Meal','meal'],[Heart,'Mood check-in','mood'],[Activity,'Movement','activity'],[Wind,'Breathe','breathe'],[Moon,'Sleep','sleep'],[Plus,'Plan a moment','event'],...(state.preferences.weightEnabled?[[Activity,'Weigh-in','weight']]:[])].map(([Icon,label,a])=>{const I=Icon as typeof Droplets;return <button key={String(a)} onClick={()=>openAction(String(a))}><I size={22}/><span>{String(label)}</span><ArrowUpRight size={15}/></button>})}</div></Modal>;
if(action==='breathe')return null
if(action==='mood'){const recent=[...state.moods].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);return <Modal title={step===1?'How are you feeling today?':'A little more context, if you want.'} onClose={onClose}><span className="eyebrow">GENTLE CHECK-IN / {step} OF 2</span>{step===1?<><p>No right answer. You can update today’s check-in whenever you want.</p><div className="mood-options">{moods.map((m,i)=><button key={m} aria-label={m} className={mood===i?'selected':''} aria-pressed={mood===i} onClick={()=>setMood(i)}><span>{moodEmoji[i]}</span>{m}</button>)}</div><button className="button" disabled={mood===null} onClick={()=>setStep(2)}>Continue <ArrowUpRight size={16}/></button>{recent.length>0&&<div className="recent-moods"><span className="tiny">YOUR RECENT CHECK-INS</span>{recent.map(m=><p key={m.id}>{moodEmoji[m.mood]} {moods[m.mood]} · {m.date}</p>)}</div>}</>:<><p>These details are optional and stay on this device. Your history can help you notice patterns.</p><label className="check-label"><input type="checkbox" checked={includeDetails} onChange={e=>setIncludeDetails(e.target.checked)}/> Add optional energy, stress, hunger, and sleep details</label>{includeDetails&&[['Energy',energy,setEnergy],['Stress',stress,setStress],['Hunger',hunger,setHunger],['Sleep quality',sleep,setSleep]].map(([label,value,set])=><label className="range-label" key={String(label)}>{String(label)} <span>{Number(value)} / 5</span><input type="range" min="1" max="5" value={Number(value)} onChange={e=>(set as (n:number)=>void)(Number(e.target.value))}/></label>)}<label>Anything you want to remember?<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)} rows={2} placeholder="A thought, a moment, a small win…"/></label>{mood!==null&&mood<=1&&<div className="gentle-support"><p>A difficult day doesn’t rewrite your story. Support is here if it would help.</p><button className="text-link" onClick={onSupport}>Find someone to talk to ↗</button></div>}<div className="actions"><button className="button" onClick={()=>{update(s=>({...s,moods:[...s.moods.filter(m=>m.date!==today),{id:uid(),date:today,mood:mood!,energy:includeDetails?energy:undefined,stress:includeDetails?stress:undefined,hunger:includeDetails?hunger:undefined,sleep:includeDetails?sleep:undefined,note}]}));finish('Check-in saved. Thank you for noticing how you feel.')}}>Save check-in <Check size={15}/></button><button className="text-link" onClick={()=>setStep(1)}>Back</button></div></>}</Modal>}
const title=action==='water'?'A sip of care.':action==='meal'?'A meal, remembered.':action==='weight'?'A number, in perspective.':action==='sleep'?'Make room for rest.':'Move in your own way.';
return <Modal title={title} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const date=String(data.get('date')||today);if(action==='water'){const ml=Number(amount)*(state.preferences.units==='imperial'?29.5735:1);update(s=>({...s,hydration:[...s.hydration,{id:uid(),date,ml:Math.round(ml)}]}));finish('Water logged. A small choice, noticed.')}else if(action==='meal'){update(s=>({...s,meals:[...s.meals,{id:uid(),date,name:String(data.get('name')).trim()}]}));finish('Meal added. Food does not need a score.')}else if(action==='weight'){const kg=Number(amount)/(state.preferences.units==='imperial'?2.20462:1);update(s=>({...s,weight_entries:[...s.weight_entries.filter(w=>w.date!==date),{id:uid(),date,kg}]}));finish('Weigh-in saved. Your longer-term trend matters more.')}else{update(s=>({...s,completed_tasks:[...s.completed_tasks,{id:uid(),date,category:action==='sleep'?'sleep':'movement',label:action==='sleep'?`${data.get('hours')} hours of rest`:`${data.get('name')} · ${data.get('minutes')} minutes`}]}));finish(action==='sleep'?'Rest noted. Be gentle with yourself.':'Movement logged. Every comfortable bit counts.')}}}>
{action==='water'&&<><p>Choose an amount that fits your glass.</p><label>Amount ({state.preferences.units==='metric'?'ml':'oz'})<input type="number" min="1" max={state.preferences.units==='metric'?3000:100} step="1" required value={amount} onChange={e=>setAmount(e.target.value)}/></label></>}
{action==='meal'&&<><label>What did you have?<input name="name" required maxLength={100} placeholder="A breakfast bowl, a sandwich…"/></label><p className="tiny">No calorie entry required. Enjoy your meal.</p></>}
{action==='weight'&&<><p>Weight is optional. You can hide all weight features in Settings.</p><label>Weight ({state.preferences.units==='metric'?'kg':'lb'})<input type="number" min="1" max={state.preferences.units==='metric'?600:1300} step=".1" required value={amount} onChange={e=>setAmount(e.target.value)}/></label></>}
{action==='activity'&&<><label>Movement<input name="name" defaultValue="Walk" required maxLength={100}/></label><label>Minutes<input name="minutes" type="number" min="1" max="1440" defaultValue="10" required/></label><p className="tiny">Adapt movement to your abilities and comfort. Rest is welcome too.</p></>}
{action==='sleep'&&<><label>Hours of rest<input name="hours" type="number" min="0" max="24" step=".5" defaultValue="7" required/></label><p className="tiny">This is a personal note, not a sleep assessment.</p></>}
<label>Date<input type="date" name="date" required defaultValue={today}/></label><button className="button" type="submit">Save <Check size={16}/></button></form>{action==='water'&&state.hydration.filter(x=>x.date===today).length>0&&<details><summary>Today’s water entries</summary>{state.hydration.filter(x=>x.date===today).map(x=><div className="list-row" key={x.id}><span>{state.preferences.units==='metric'?x.ml+' ml':Math.round(x.ml/29.5735)+' oz'}</span><button className="icon-button" aria-label={`Remove water entry ${x.ml} ml`} onClick={()=>update(s=>({...s,hydration:s.hydration.filter(w=>w.id!==x.id)}))}>×</button></div>)}</details>}</Modal>}
