export const LEGAL_VERSION='2026-10-06.1';
export const legalSources=[
{title:'Colorado Privacy Act',region:'Colorado',url:'https://coag.gov/resources/colorado-privacy-act/',note:'Applicability depends on statutory thresholds and activity. Sensitive-data consent, purpose limitation, access/correction/deletion/portability, appeals and universal opt-outs require review.'},
{title:'Colorado data protection and breach duties',region:'Colorado',url:'https://coag.gov/resources/data-protection-laws/',note:'Reasonable security, disposal and incident duties can apply separately from CPA thresholds. Colorado breach timing can be shorter than HIPAA timing.'},
{title:'CCPA / CPRA',region:'California',url:'https://oag.ca.gov/privacy/ccpa',note:'Thresholds and exceptions require review. Where covered, notice, access, correction, deletion, sensitive-data limits and sale/sharing opt-outs apply.'},
{title:'Global Privacy Control',region:'California / Colorado',url:'https://www.oag.ca.gov/privacy/ccpa/gpc',note:'HealthUp does not sell data or use targeted advertising. Browser opt-out signals are honored without asking for extra identity data.'},
{title:'My Health My Data Act',region:'Washington',url:'https://www.atg.wa.gov/protecting-washingtonians-personal-health-data-and-privacy',note:'Consumer-health-data rules may reach out-of-state apps. Collection and sharing need separate analysis; health-data sale authorization is distinct. No health-data sales are supported.'},
{title:'NRS Chapter 603A',region:'Nevada',url:'https://www.leg.state.nv.us/NRS/NRS-603A.html',note:'Consumer-health notice, consent, rights, deletion and processor duties require a Nevada-specific review.'},
{title:'Health app developers and HIPAA',region:'United States',url:'https://www.hhs.gov/hipaa/for-professionals/special-topics/health-apps/index.html',note:'HIPAA is determined by covered-entity/business-associate relationships, not by adding a disclaimer or encryption. HealthUp makes no HIPAA compliance certification.'},
{title:'FTC Health Breach Notification Rule',region:'United States',url:'https://www.ftc.gov/business-guidance/resources/complying-ftcs-health-breach-notification-rule-0',note:'The amended rule can cover non-HIPAA health apps, including apps with information from multiple sources. Incident response needs legal assessment, notices and operational ownership.'},
{title:'FDA general wellness guidance — January 2026',region:'United States',url:'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/general-wellness-policy-low-risk-devices',note:'Keep intended use in low-risk wellness. Claims and functionality, not disclaimers alone, determine device status.'},
{title:'Children’s privacy — COPPA',region:'United States',url:'https://www.ftc.gov/business-guidance/resources/complying-coppa-frequently-asked-questions',note:'Initial account registration is adult-only. An age statement alone cannot excuse actual knowledge or child-directed marketing.'},
{title:'Australian mobile-app privacy',region:'Australia',url:'https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/more-guidance/mobile-privacy-a-better-practice-guide-for-mobile-app-developers',note:'Assess APP coverage, sensitive-information consent, cross-border disclosures, retention and breach duties before offering accounts in Australia.'},
{title:'LGPD regulator guidance',region:'Brazil',url:'https://www.gov.br/anpd/pt-br/acesso-a-informacao/perguntas-frequentes',note:'Assess sensitive-data legal bases, rights, controller duties and international transfers; no Brazil account launch is enabled by default.'},
{title:'POPIA guidance',region:'South Africa',url:'https://inforegulator.org.za/guidance-notes/',note:'Review special personal information, lawful processing, information-officer and transfer duties before local account availability.'},
{title:'DPDP Rules 2025',region:'India',url:'https://www.meity.gov.in/content/digital-personal-data-protection-rules-2025',note:'Check the official commencement schedule and implementing duties at launch; do not assume every provision commenced together.'},
{title:'GDPR official text',region:'EU / EEA',url:'https://eur-lex.europa.eu/eli/reg/2016/679/oj/eng',note:'Article 6 lawful basis and Article 9 health-data condition are distinct. Explicit consent, withdrawal, rights, DPIA, processors, representatives and international transfers require assessment before offering accounts there.'},
{title:'UK special-category data',region:'United Kingdom',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/lawful-basis/special-category-data/',note:'UK GDPR and DPA conditions, UK representative/transfer duties and PECR must be assessed. No worldwide compliance is asserted.'},
{title:'Meaningful consent under PIPEDA',region:'Canada',url:'https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/p_principle/principles/p_consent/',note:'Express consent is generally appropriate for sensitive information; provincial rules such as Québec Law 25 also need assessment.'},
{title:'California automatic-renewal protections',region:'California',url:'https://oag.ca.gov/node/608083',note:'Review 2025 amendments, affirmative consent, confirmations, reminders and simple cancellation before charging subscriptions.'},
{title:'FTC subscription rulemaking — March 2026',region:'United States',url:'https://www.ftc.gov/news-events/news/press-releases/2026/03/ftc-seeks-public-comment-response-advance-notice-proposed-rulemaking-regarding-negative-option',note:'The 2024 amended rule was vacated. ROSCA and other consumer-protection duties still require clear terms, informed consent and simple cancellation; do not rely on the vacated rule as current law.'}
];
export const policySections=[
{title:'What HealthUp is',text:'HealthUp offers general wellness planning and reflection. The operator is not presented as a doctor, therapist, dietitian, medical provider, or emergency service. The app does not diagnose, treat, monitor, or prevent conditions. Check-ins, trends, calorie estimates and suggested content are informational. Do not delay professional care.'},
{title:'What stays on your device',text:'Wellness entries, calendar events, recipes, journals, dreams and preferences are saved locally. Device storage uses AES-GCM encryption with a non-extractable browser-held key. Anyone with access to your unlocked browser or compromised site code may still access the app. This is not end-to-end encryption, a medical record, or a substitute for a device passcode. Exported plain JSON backups contain personal information.'},
{title:'Account data, when enabled',text:'Registration requires an adult age confirmation, accepted service terms, a wellness acknowledgement and consent to essential account processing. The account service stores encrypted email, display name and consent records; passwords use Argon2 hashing. Sessions use secure cookies. Verification/reset emails use the configured transactional email provider. Registration stays disabled until operator identity, email, deployment and legal-review settings are complete.'},
{title:'Optional encrypted cloud backup',text:'Cloud backup is a separate opt-in and is off by default. When enabled for a paid account, the backup can contain all exported wellness entries, including moods, weight, journal and dream text. The backend encrypts backups at rest and the hosting processor handles them to provide backup/restore. The server holds the encryption key; this is not end-to-end encryption. Withdraw this consent to delete the stored backup and disable uploads. Declining does not disable core tools.'},
{title:'No sale, targeted ads, or tracking pixels',text:'HealthUp has no third-party analytics or advertising SDKs, does not sell wellness data, and does not use health information for targeted advertising. Global Privacy Control is honored. This app has no optional advertising cookies to accept. Essential session cookies are used only when accounts are enabled.'},
{title:'External providers and resources',text:'GitHub Pages serves the public app and receives ordinary network information such as IP address. A configured Railway service receives API requests. Optional food/research searches send search terms to USDA or NCBI through the backend. Avoid putting personal health details into those search boxes. Stripe handles payment information when billing is configured; HealthUp does not receive full card details. External resources have independent privacy policies. Fonts and core wellness content are bundled locally.'},
{title:'Your choices and rights',text:'Use Settings to export, correct and delete local data. Signed-in accounts provide account export, consent history, session revocation, backup deletion, and account deletion. Privacy requests and appeals can be submitted through the authenticated request form when the account service is enabled. Region-specific rights and deadlines must be assessed by the operator. Declining optional sharing will not block core wellness tools. Withdrawing essential account consent closes the account; you can keep local tools.'},
{title:'Retention and security limitations',text:'Local records remain until you delete them or the browser clears storage. Active account records remain until deletion. Reset tokens expire after 30 minutes; sessions expire after seven days. Security rate-limit records expire after one hour; staff audit and closed privacy-request records are purged after 90 days by the maintenance job. Backups are replaced on upload and removed on withdrawal or account deletion. Encrypted infrastructure backups, if used, require a documented expiry schedule before production activation. Stripe may retain payment records under its own legal obligations; deleting your HealthUp account does not promise deletion of legally required billing records. No system can promise perfect security.'},
{title:'Personalized suggestions and check-ins',text:'Suggestions use a transparent local rule based on your latest mood check-in, category preferences and recent activities. They are not clinical assessments, diagnoses, or decisions about eligibility. Turn personalization off in Settings. The post-login check-in is shown before continuing; “Prefer not to say” is available. Entries are not watched by staff and no one is automatically contacted.'},
{title:'Subscriptions and cancellation',text:'The free core includes water, food, journey, mood, local journals and crisis resources. HealthUp Plus adds encrypted cloud backup and restore when connected. Price, billing interval and cancellation terms must be shown before purchase, with a separate renewal acknowledgement. Stripe’s billing portal provides cancellation. Billing stays disabled until a configured price, verified webhooks, provider portal, contact information and reviewed terms are present.'},
{title:'Service terms and acknowledgement',text:'Use tools within your abilities, stop if uncomfortable and seek qualified advice where needed. You acknowledge the wellness purpose and that the app is not monitored or suitable for emergencies. There is no guarantee of a specific health outcome or uninterrupted service. Nothing here waives non-waivable privacy, consumer or other statutory rights, or excludes liability that cannot lawfully be excluded. An acknowledgement is not blanket legal immunity. You retain applicable consumer and privacy rights even after signing.'},
{title:'Regional launch and review status',text:'These notices describe the implemented system and remain subject to operator legal review. The account service defaults to United States adults only until the operator approves additional regions. Local execution does not automatically remove privacy-law duties. This is not a claim that every applicable law worldwide has been satisfied. A production account launch requires a named operator, privacy contact, retention/incident process, processor contracts and a documented jurisdiction review.'}
];
