import type {Category,State} from './types';
import {dateKey,shiftDate} from './logic';
export interface Practice {id:string;name:string;category:Category;steps:string[];minutes:number}
const templates:{id:string;name:string;category:Category;steps:string[]}[]=[
{id:'sound',name:'Listen to the room',category:'mindfulness',steps:['Settle somewhere comfortable; keep your eyes open or softly closed.','Notice a nearby sound, then one further away. Let both come and go.','Return to the room without needing to change how you feel.']},
{id:'ground',name:'A gentle grounding pause',category:'mindfulness',steps:['Feel the support under your feet or body.','Notice five neutral things you can see. Choose fewer if that feels easier.','Notice a texture and a sound. End whenever you need.']},
{id:'breath',name:'An easy breathing moment',category:'mindfulness',steps:['Let your breathing stay natural and comfortable.','If comfortable, let your exhale become a little softer. No holds are needed.','Return to your normal rhythm. Stop if uncomfortable or dizzy.']},
{id:'rest',name:'Do a little less',category:'selfcare',steps:['Find a comfortable position and set one demand aside.','You do not need to achieve anything during this pause.','Ask yourself what would make the next moment easier.']},
{id:'shoulders',name:'A little shoulder space',category:'movement',steps:['Sit or stand with support; stay within a comfortable range.','Gently roll or relax your shoulders. Skip movement that hurts.','Rest your arms and notice your comfort.']},
{id:'walk',name:'A walk at your own pace',category:'movement',steps:['Choose a safe, accessible route; seated movement is welcome instead.','Move at a comfortable pace, noticing the light or surroundings.','Slow down before finishing and rest when you need.']},
{id:'gratitude',name:'One ordinary thing',category:'selfcare',steps:['Think of a neutral or pleasant moment, however small.','Write or remember one thing that supported you. Gratitude need not feel forced.','Let that be enough for now.']},
{id:'tidy',name:'Make one corner kinder',category:'selfcare',steps:['Choose one small space, such as a bedside table.','Put away just a few things or make room for something helpful.','Stop at the timer. A little space is enough.']},
{id:'sip',name:'A mindful sip',category:'hydration',steps:['Bring a drink you enjoy; follow any clinician fluid guidance.','Take comfortable sips, noticing temperature and taste. No need to finish it.','Keep it nearby if that helps; record water only if you drank it.']},
{id:'meal',name:'A pause before food',category:'nutrition',steps:['Make yourself comfortable and set aside a distraction if you wish.','Notice the colors, smells, or textures of food.','Enjoy at your own pace. This practice does not require calorie tracking.']},
{id:'winddown',name:'A softer landing',category:'sleep',steps:['Lower stimulation where you comfortably can.','Write down one thing that can wait until tomorrow.','Choose a small next step toward rest.']},
{id:'connect',name:'A small connection',category:'selfcare',steps:['Think of someone safe you would like to connect with.','Draft a simple hello, or think about reaching out later.','Send only if you want. You are allowed to keep this moment private.']}
];
export function choosePractice(minutes:number,category:string='all',history:string[]=[],random=Math.random):Practice {const n=Math.max(1,Math.min(60,Math.round(minutes)));const pool=templates.filter(p=>category==='all'||p.category===category);const recent=new Set([...new Set(history.filter(id=>pool.some(p=>p.id===id)).reverse())].slice(0,Math.max(1,pool.length-1)));const fresh=pool.filter(p=>!recent.has(p.id));const choices=fresh.length?fresh:pool;const selected=choices[Math.min(choices.length-1,Math.floor(random()*choices.length))]||templates[0];return {...selected,minutes:n,name:`${n}-minute ${selected.name.toLowerCase()}`,steps:selected.steps.map((step,i)=>`${Math.floor(n*60*i/3)}–${Math.floor(n*60*(i+1)/3)} seconds · ${step}`)};}
export function nextFresh<T extends {id:string}>(items:T[],history:string[],random=Math.random):T{const ids=new Set(items.map(x=>x.id));const seen=new Set([...new Set(history.filter(id=>ids.has(id)).reverse())].slice(0,Math.max(1,items.length-1)));const choices=items.filter(x=>!seen.has(x.id));const pool=choices.length?choices:items;return pool[Math.min(pool.length-1,Math.floor(random()*pool.length))]}
export function careRecommendations(state:State){const mood=state.moods.find(m=>m.date===dateKey());if(!state.wellness.personalization||!mood)return ['habits','selfcare','hydration'];return mood.mood<=1?['selfcare','mindfulness','sleep']:mood.mood===2?['mindfulness','hydration','habits']:['movement','nutrition','habits']}
export function returningStats(state:State){const dates=new Set([...state.moods.map(m=>m.date),...state.completed_tasks.map(t=>t.date),...state.hydration.map(h=>h.date)]);let consecutive=0;let date=dateKey();if(!dates.has(date))date=shiftDate(date,-1);while(dates.has(date)&&consecutive<1000){consecutive++;date=shiftDate(date,-1)}return {consecutive,total:dates.size,last7:Array.from({length:7},(_,i)=>({date:shiftDate(dateKey(),i-6),active:dates.has(shiftDate(dateKey(),i-6))}))}}
