import {useState} from 'react';
import {Heart,Phone,ExternalLink} from 'lucide-react';
import {useHealth} from './store';
import {Heading,Pill} from './ui';
import {WellnessArt} from './Studio';
const resources=[
{country:'US',title:'988 Suicide & Crisis Lifeline',detail:'Call or text 988 in the United States. For immediate danger, call 911.',url:'https://988lifeline.org/get-help/',phone:'988'},
{country:'US',title:'Find treatment through SAMHSA',detail:'A US directory for mental health and substance-use treatment. Availability and cost vary.',url:'https://findtreatment.gov/',phone:''},
{country:'US',title:'Colorado 988',detail:'Colorado support through the national 988 service.',url:'https://988colorado.com/',phone:'988'},
{country:'US',title:'NAMI support and education',detail:'Information, peer support, and resources. Not an emergency response service.',url:'https://www.nami.org/support-education/',phone:''},
{country:'CA',title:'Canada 9-8-8',detail:'Call or text 988 in Canada. For immediate danger, call 911.',url:'https://988.ca/',phone:'988'},
{country:'UK',title:'Samaritans',detail:'Call 116 123 in the UK or Ireland. For immediate danger use 999 or 112.',url:'https://www.samaritans.org/how-we-can-help/contact-samaritan/',phone:'116123'},
{country:'AU',title:'Lifeline Australia',detail:'Call 13 11 14 in Australia. For immediate danger use 000.',url:'https://www.lifeline.org.au/',phone:'131114'},
{country:'GLOBAL',title:'Find a Helpline',detail:'Look up verified support options in your own country. Numbers and availability vary.',url:'https://findahelpline.com/',phone:''},
{country:'GLOBAL',title:'Befrienders Worldwide',detail:'An international directory of emotional support services.',url:'https://befrienders.org/',phone:''},
{country:'GLOBAL',title:'WHO mental health information',detail:'Public mental health information and perspectives, not individualized care.',url:'https://www.who.int/health-topics/mental-health',phone:''}
];
export default function Resources(){const {state,update}=useHealth();const [region,setRegion]=useState(state.preferences.supportRegion||'US');return <><Heading eyebrow="REAL SUPPORT / REAL PEOPLE" title="You do not have to" italic="carry it alone."><p>HealthUp is a wellness app. It does not monitor entries or replace qualified care. These links connect you to outside services.</p></Heading><section className="card urgent-resource"><Heart size={25}/><div><h2>If you need help <em>right now.</em></h2><p>If you may act on thoughts of suicide or are in immediate danger, call your local emergency number or go to an emergency department. Reach someone you trust if you can.</p></div></section><div className="filter-row">{[['US','United States'],['CA','Canada'],['UK','UK / Ireland'],['AU','Australia'],['GLOBAL','Worldwide']].map(([id,label])=><Pill key={id} active={region===id} onClick={()=>{setRegion(id);update(s=>({...s,preferences:{...s.preferences,supportRegion:id}}))}}>{label}</Pill>)}</div><div className="guide-grid">{resources.filter(r=>r.country===region||r.country==='GLOBAL').map((r,i)=><article className="card resource-card" key={r.title}>{i===0&&<WellnessArt scene={6} label="Interlocking aqua glass loops representing connection"/>}<span className="eyebrow">{r.country==='GLOBAL'?'GLOBAL DIRECTORY':r.country+' / SUPPORT'}</span><h2>{r.title}</h2><p>{r.detail}</p><div className="actions">{r.phone&&<a className="button" href={`tel:${r.phone}`}><Phone size={15}/> Call {r.phone}</a>}<a className="text-link" href={r.url} target="_blank" rel="noreferrer">Official service <ExternalLink size={13}/></a></div></article>)}</div><p className="tiny">External services have their own privacy policies and eligibility requirements. HealthUp does not transfer your journal or check-in data when you open these links.</p></>}
