import {openDB} from 'idb';
import type {State} from './types';
import {defaultState} from './logic';
const stores=['profile','preferences','hydration','weight_entries','moods','completed_tasks','favorites','calendar_events','journey','notification_preferences','intentions','reflections','meals','timer'] as const;
const dbPromise=openDB('healthup',1,{upgrade(db){for(const name of stores)db.createObjectStore(name)}});
export const IndexedDBAdapter={async load():Promise<State>{const db=await dbPromise;const state=defaultState();for(const key of stores){const value=await db.get(key,'current');if(value!==undefined)(state as unknown as Record<string,unknown>)[key]=value}return state},async save(state:State){const db=await dbPromise;const tx=db.transaction([...stores],'readwrite');await Promise.all(stores.map(key=>tx.objectStore(key).put(state[key],'current')));await tx.done},async clear(){const db=await dbPromise;const tx=db.transaction([...stores],'readwrite');for(const key of stores)await tx.objectStore(key).clear();await tx.done}};
const API=import.meta.env.VITE_API_URL==='same-origin'?location.origin:(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
async function cachedRequest(path:string,key:string){try{if(!API)throw new Error('Backend not connected');const r=await fetch(`${API}${path}`,{signal:AbortSignal.timeout(8000),credentials:'omit'});if(!r.ok)throw new Error('Service unavailable');const data=await r.json();try{localStorage.setItem(key,JSON.stringify(data))}catch{}return {data,cached:false}}catch{try{const stored=localStorage.getItem(key);if(stored)return {data:JSON.parse(stored),cached:true}}catch{}throw new Error('Live service unavailable. Bundled content is still available.')}}
export const USDAAdapter={search:(query:string)=>cachedRequest(`/api/foods/search?q=${encodeURIComponent(query)}`,'healthup-food-'+query.toLowerCase())};
export const PubMedAdapter={search:(query:string)=>cachedRequest(`/api/research?q=${encodeURIComponent(query)}`,'healthup-research-'+query.toLowerCase())};
export const NotificationAdapter={async request(){if(!('Notification'in window))return 'unsupported';return Notification.requestPermission()},async notify(title:string,body:string){if(!('Notification'in window)||Notification.permission!=='granted')return;try{const registration=await navigator.serviceWorker?.ready;if(registration)await registration.showNotification(title,{body,icon:new URL('assets/icon.svg',location.href).href,tag:body});else new Notification(title,{body})}catch{/* In-app reminders remain available. */}}};
export const CalendarAdapter={download(events:State['calendar_events']){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//HealthUp//Local Calendar//EN'];const esc=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');for(const e of events){lines.push('BEGIN:VEVENT',`UID:${e.id}@healthup`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').split('.')[0]}Z`,`DTSTART:${e.date.replace(/-/g,'')}T${e.time.replace(':','')}00`,`DURATION:PT${e.duration}M`,`SUMMARY:${esc(e.title)}`);if(e.repeat!=='none')lines.push(`RRULE:FREQ=${e.repeat==='daily'?'DAILY':'WEEKLY'}`);for(const date of e.excluded)lines.push(`EXDATE:${date.replace(/-/g,'')}T${e.time.replace(':','')}00`);lines.push('END:VEVENT')}lines.push('END:VCALENDAR');download('healthup-calendar.ics',lines.join('\r\n'),'text/calendar')}};
export function download(name:string,body:string,type='application/json'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
