import {useState} from 'react';
import {Droplets,Utensils,Activity,Wind,Heart,Check,Plus,ArrowUpRight,Moon,Sun} from 'lucide-react';
import {useHealth} from './store';
import {balance,dateKey,waterTotal,eventsOn,uid,hydrationSlots} from './logic';
import {thought,selfcare} from './content';
import {Heading} from './ui';
export default function Today(){const {state,update,openAction,go,notify}=useHealth();const today=dateKey();const score=balance(state);const water=waterTotal(state);const fraction=Math.min(1,water/state.preferences.waterTarget);const upcoming=eventsOn(state.calendar_events,today);const [care,setCare]=useState(selfcare[0]);const [available,setAvailable]=useState(10);const hour=new Date().getHours();const day=Math.max(1,Math.min(100,Math.floor((Date.now()-new Date(state.profile.start+'T00:00:00').getTime())/86400000)+1));const done=(category:string)=>state.completed_tasks.some(t=>t.date===today&&t.category===category);const addCare=()=>{update(s=>({...s,completed_tasks:[...s.completed_tasks,{id:uid(),date:today,category:'selfcare',label:care.text}]}));notify('A little care, noticed.');};const slots=hydrationSlots(state.preferences.wake,state.preferences.sleep,state.preferences.reminderMinutes);return <>
<Heading eyebrow={`${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase()} / DAY ${day} OF 100`} title={`Good ${hour<12?'morning':hour<18?'afternoon':'evening'}${state.profile.name?', '+state.profile.name:''}.`} italic="How are you feeling?"><p>Your health is bigger than a number. Let’s take care of the next decision.</p></Heading>
<div className="dashboard-grid"><section className="card balance-card"><div className="card-top"><span className="eyebrow">YOUR DAILY BALANCE</span><span className="tiny">Personal · optional</span></div><div className="balance-content"><div className="balance-ring" role="img" aria-label={`${score}% personal daily balance`}><svg viewBox="0 0 200 200"><circle className="ring-track" cx="100" cy="100" r="84"/><circle className="ring-value" cx="100" cy="100" r="84" strokeDasharray="528" strokeDashoffset={528*(1-score/100)}/></svg><div><strong>{score}<small>%</small></strong><span>DAILY BALANCE</span></div></div><div><h2>A little more<br/><em>in balance.</em></h2><p>A reflection of the categories you choose.<br/>A gentle guide, never a medical score.</p><button className="text-link" onClick={()=>go('settings')}>Choose your categories <ArrowUpRight size={14}/></button></div></div><div className="category-row">{state.preferences.categories.map(c=><span key={c} className={c==='hydration'&&fraction>=1||c==='nutrition'&&state.meals.some(m=>m.date===today)||done(c)?'met':''}><span className="dot"/>{c==='selfcare'?'Self-care':c}</span>)}</div></section>
<section className="card hydration-card"><div className="card-top"><span className="eyebrow">A SIP OF SOMETHING GOOD</span><Droplets size={19}/></div><h2>Stay <em>hydrated.</em></h2><div className="water-vessel" role="img" aria-label={`${Math.round(water)} milliliters logged`}><div className="water-fill" style={{transform:`scaleY(${fraction})`}}/><Droplets size={38}/></div><div className="water-stat"><strong>{state.preferences.units==='metric'?Math.round(water):Math.round(water/29.5735)}<small>{state.preferences.units==='metric'?'ml':'oz'}</small></strong><span>of {state.preferences.units==='metric'?state.preferences.waterTarget:Math.round(state.preferences.waterTarget/29.5735)} {state.preferences.units==='metric'?'ml':'oz'}</span></div><div className="water-buttons">{[237,355,473].map((ml,i)=><button key={ml} onClick={()=>{update(s=>({...s,hydration:[...s.hydration,{id:uid(),date:today,ml}]}));notify('Water logged. Every sip counts.')}}>+ {state.preferences.units==='metric'?`${ml} ml`:`${[8,12,16][i]} oz`}</button>)}<button aria-label="Log custom water amount" onClick={()=>openAction('water')}><Plus size={15}/></button></div><p className="tiny">{fraction>=1?'Your chosen target is reached. No more reminders today.':fraction>=.5?'Halfway there. Grab some water when you get a chance.':'Keep some water nearby, whenever it fits.'}</p></section></div>
<section className="quick-actions" aria-label="Quick logging">{[[Droplets,'Water','water'],[Utensils,'Meal','meal'],[Heart,'Mood','mood'],[Activity,'Activity','activity'],[Wind,'Breathe','breathe'],...(state.preferences.weightEnabled?[[Activity,'Weight','weight']]:[])].map(([Icon,label,action])=>{const I=Icon as typeof Droplets;return <button key={String(action)} onClick={()=>openAction(String(action))}><I size={19}/><span>+ {String(label)}</span></button>})}</section>
<div className="two-columns"><section className="card"><div className="card-top"><span className="eyebrow">A LITTLE STRUCTURE</span><button className="text-link" onClick={()=>go('calendar')}>Your calendar ↗</button></div><h2>Coming <em>up.</em></h2>{upcoming.length?upcoming.slice(0,4).map(e=><div className="timeline-row" key={e.id}><span>{e.time}</span><div><strong>{e.title}</strong><small>{e.type}</small></div><button className="icon-button" aria-label={`Complete ${e.title}`} onClick={()=>{update(s=>({...s,calendar_events:s.calendar_events.map(x=>x.id===e.id?{...x,completed:[...new Set([...x.completed,today])]}:x)}));notify('One helpful moment, complete.')}}>{e.completed.includes(today)?<Check size={17}/>:<span className="check-circle"/>}</button></div>):<p>No plans yet. Leave room for your day, or add one gentle reminder.</p>}<button className="button secondary" onClick={()=>openAction('event')}>Plan a moment <Plus size={15}/></button>{fraction<1&&<p className="tiny">Water breaks suggested around {slots.slice(0,3).join(' · ')}. Customize in Settings.</p>}</section>
<section className="card thought-card"><span className="eyebrow">TODAY’S THOUGHT</span><h2><em>“{thought}”</em></h2><span className="tiny">NO PERFECTION REQUIRED.</span><div className="natural-small" aria-hidden="true"/></section></div>
<div className="three-columns"><section className="card"><span className="eyebrow">FOOD, WITHOUT RULES</span><h2>Today’s <em>meals.</em></h2>{state.meals.filter(m=>m.date===today).map(m=><div className="list-row" key={m.id}><span>{m.name}</span><button aria-label={`Remove ${m.name}`} className="icon-button" onClick={()=>update(s=>({...s,meals:s.meals.filter(x=>x.id!==m.id)}))}>×</button></div>)}{!state.meals.some(m=>m.date===today)&&<p>What sounds nourishing today?</p>}<button className="text-link" onClick={()=>go('food')}>Explore 100 recipes ↗</button></section><section className="card"><span className="eyebrow">YOUR NEXT SMALL STEP</span><h2>A daily <em>intention.</em></h2><label className="sr-only" htmlFor="intention">Daily intention</label><textarea id="intention" rows={2} value={state.intentions[today]||''} onChange={e=>update(s=>({...s,intentions:{...s.intentions,[today]:e.target.value}}))} placeholder="Today, I want to make room for…"/><div className="habit-buttons"><button onClick={()=>openAction('activity')}><Activity size={15}/> Movement</button><button onClick={()=>openAction('sleep')}><Moon size={15}/> Rest</button></div></section><section className="card"><span className="eyebrow">CARE YOU CAN ACTUALLY DO</span><h2>Just for <em>you.</em></h2><label htmlFor="care-time" className="tiny">Time available</label><select id="care-time" value={available} onChange={e=>setAvailable(Number(e.target.value))}>{[2,5,10,20].map(n=><option key={n} value={n}>{n} minutes</option>)}</select><p className="care-prompt">{care.text}</p><div className="actions"><button className="text-link" onClick={()=>{const choices=selfcare.filter(c=>c.minutes<=available);setCare(choices[Math.floor(Math.random()*choices.length)])}}>Give me something ↻</button><button className="icon-button" aria-label="Complete self-care" onClick={addCare}><Check size={18}/></button></div></section></div>
<section className="card reflection"><Sun size={24}/><div><span className="eyebrow">BEFORE THE DAY SETTLES</span><h2>An evening <em>reflection.</em></h2></div><label className="sr-only" htmlFor="reflection">Evening reflection</label><textarea id="reflection" value={state.reflections[today]||''} onChange={e=>update(s=>({...s,reflections:{...s.reflections,[today]:e.target.value}}))} placeholder="What helped today? What might feel easier tomorrow?" rows={2}/></section>
</>}
